# Generated by Django 3.0.5 on 2021-03-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedUsersGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('groupid', models.CharField(max_length=255)),
            ],
        ),
    ]
