# Generated by Django 3.0.5 on 2021-03-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_boughtedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
