# Generated by Django 3.0.5 on 2021-03-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0008_productgroup_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail1',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail2',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail3',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
