# Generated by Django 3.0.5 on 2021-03-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0009_auto_20210329_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='thumbnail1',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='content',
            name='thumbnail2',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='content',
            name='thumbnail3',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
